// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD84i03kClDaq2wL3oeKQxjuKGM1dqb1Y',
    appId: '1:746333542346:web:5e83d6d4b8b5e027c8a133',
    messagingSenderId: '746333542346',
    projectId: 'smartstudent-finance',
    authDomain: 'smartstudent-finance.firebaseapp.com',
    storageBucket: 'smartstudent-finance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDFKi2C2kkxcjAx_DSEcBqKQ3ubUxKhB8',
    appId: '1:746333542346:android:9f55f9ed93e07167c8a133',
    messagingSenderId: '746333542346',
    projectId: 'smartstudent-finance',
    storageBucket: 'smartstudent-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwhGvcqdyYGpuRl89fNREgneSHxGFt03M',
    appId: '1:746333542346:ios:f51a3504db33e036c8a133',
    messagingSenderId: '746333542346',
    projectId: 'smartstudent-finance',
    storageBucket: 'smartstudent-finance.firebasestorage.app',
    iosBundleId: 'com.uca.aplikasiKeuanganMahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwhGvcqdyYGpuRl89fNREgneSHxGFt03M',
    appId: '1:746333542346:ios:f51a3504db33e036c8a133',
    messagingSenderId: '746333542346',
    projectId: 'smartstudent-finance',
    storageBucket: 'smartstudent-finance.firebasestorage.app',
    iosBundleId: 'com.uca.aplikasiKeuanganMahasiswa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD84i03kClDaq2wL3oeKQxjuKGM1dqb1Y',
    appId: '1:746333542346:web:4760152ee2a2321cc8a133',
    messagingSenderId: '746333542346',
    projectId: 'smartstudent-finance',
    authDomain: 'smartstudent-finance.firebaseapp.com',
    storageBucket: 'smartstudent-finance.firebasestorage.app',
  );
}
